#!/usr/bin/env python3
"""Generate PCEdit.App.Core/Data/ItemCatalog.json from a curated mapping.

The GId list was seeded from PCEdit.SaveFileHandler/Standard-2.json (world
objects + unlockedGroups + inventory demand/supply groups). Curate here, then
this script writes the JSON the app embeds. Re-run after editing the tables.
"""
import json
import collections

CATEGORIES = collections.OrderedDict([
    ("ore",        {"displayName": "Ore & Minerals",     "icon": "cat_ore.png"}),
    ("gem",        {"displayName": "Rare Crystals",       "icon": "cat_gem.png"}),
    ("component",  {"displayName": "Crafted Components",  "icon": "cat_component.png"}),
    ("seed",       {"displayName": "Seeds",               "icon": "cat_seed.png"}),
    ("plant",      {"displayName": "Plants & Microbes",   "icon": "cat_plant.png"}),
    ("food",       {"displayName": "Food & Water",        "icon": "cat_food.png"}),
    ("larva",      {"displayName": "Larvae & Eggs",       "icon": "cat_larva.png"}),
    ("structure",  {"displayName": "Structures & Machines","icon": "cat_structure.png"}),
    ("furniture",  {"displayName": "Furniture & Decor",   "icon": "cat_furniture.png"}),
    ("equipment",  {"displayName": "Equipment & Gear",    "icon": "cat_equipment.png"}),
    ("consumable", {"displayName": "Consumables & Fuses", "icon": "cat_consumable.png"}),
    ("rocket",     {"displayName": "Rockets",             "icon": "cat_rocket.png"}),
    ("token",      {"displayName": "Terra Tokens",        "icon": "cat_token.png"}),
    ("chip",       {"displayName": "Chips & Blueprints",  "icon": "cat_chip.png"}),
    ("container",  {"displayName": "Storage Crates",      "icon": "cat_container.png"}),
    ("vehicle",    {"displayName": "Vehicles & Upgrades", "icon": "cat_vehicle.png"}),
    ("misc",       {"displayName": "Miscellaneous",       "icon": "cat_misc.png"}),
])
FALLBACK_CATEGORY = "misc"

# gid -> (displayName, category). Order preserved for readability in the file.
ITEMS = collections.OrderedDict([
    # --- Ore & minerals ---
    ("Iron", ("Iron", "ore")),
    ("Cobalt", ("Cobalt", "ore")),
    ("Titanium", ("Titanium", "ore")),
    ("Aluminium", ("Aluminium", "ore")),
    ("Silicon", ("Silicon", "ore")),
    ("Magnesium", ("Magnesium", "ore")),
    ("Sulfur", ("Sulfur", "ore")),
    ("Iridium", ("Iridium", "ore")),
    ("Osmium", ("Osmium", "ore")),
    ("Uranim", ("Uranium", "ore")),
    ("Zeolite", ("Zeolite", "ore")),
    ("Obsidian", ("Obsidian", "ore")),
    ("ice", ("Ice", "ore")),
    # --- Rare crystals ---
    ("PulsarQuartz", ("Pulsar Quartz", "gem")),
    ("SolarQuartz", ("Solar Quartz", "gem")),
    ("MagnetarQuartz", ("Magnetar Quartz", "gem")),
    # --- Crafted components ---
    ("Alloy", ("Alloy", "component")),
    ("Rod-alloy", ("Alloy Rod", "component")),
    ("Rod-iridium", ("Iridium Rod", "component")),
    ("Rod-uranium", ("Uranium Rod", "component")),
    ("CircuitBoard1", ("Circuit Board", "component")),
    ("Bioplastic1", ("Bioplastic Nugget", "component")),
    ("FabricBlue", ("Fabric", "component")),
    ("Silk", ("Silk", "component")),
    ("RedPowder1", ("Explosive Powder", "component")),
    ("Fertilizer1", ("Fertilizer T1", "component")),
    ("Fertilizer2", ("Fertilizer T2", "component")),
    ("Mutagen1", ("Mutagen T1", "component")),
    ("Mutagen2", ("Mutagen T2", "component")),
    ("FusionEnergyCell", ("Fusion Energy Cell", "component")),
    ("Bacteria1", ("Bacteria Sample", "component")),
    # --- Seeds ---
    ("Seed0", ("Seed (Common)", "seed")),
    ("Seed1", ("Seed", "seed")),
    ("Seed2", ("Seed", "seed")),
    ("Seed3", ("Seed", "seed")),
    ("Seed4", ("Seed", "seed")),
    ("Seed6", ("Seed", "seed")),
    ("Seed7Humble", ("Humble Seed", "seed")),
    ("Seed8Humble", ("Humble Seed", "seed")),
    ("SeedGold", ("Golden Seed", "seed")),
    ("Algae1Seed", ("Algae Spores", "seed")),
    ("CookCocoaSeed", ("Cocoa Seed", "seed")),
    ("CookWheatSeed", ("Wheat Seed", "seed")),
    ("Tree1Seed", ("Tree Seed", "seed")),
    ("Tree2Seed", ("Tree Seed", "seed")),
    ("Tree8Seed", ("Tree Seed", "seed")),
    ("Vegetable0Seed", ("Vegetable Seed", "seed")),
    ("Vegetable1Seed", ("Vegetable Seed", "seed")),
    ("Vegetable2Seed", ("Vegetable Seed", "seed")),
    ("Vegetable3Seed", ("Vegetable Seed", "seed")),
    # --- Plants & microbes ---
    ("Vegetable0Growable", ("Growing Vegetable", "plant")),
    ("Vegetable1Growable", ("Growing Vegetable", "plant")),
    ("Vegetable2Growable", ("Growing Vegetable", "plant")),
    ("Vegetable3Growable", ("Growing Vegetable", "plant")),
    ("TreeRoot", ("Tree Root", "plant")),
    ("Phytoplankton1", ("Phytoplankton", "plant")),
    ("Phytoplankton2", ("Phytoplankton", "plant")),
    ("Phytoplankton3", ("Phytoplankton", "plant")),
    # --- Food & water ---
    ("astrofood", ("Space Food", "food")),
    ("honey", ("Honey", "food")),
    ("WaterBottle1", ("Water Bottle", "food")),
    # --- Larvae & eggs ---
    ("Bee1Larvae", ("Bee Larva", "larva")),
    ("Butterfly1Larvae", ("Butterfly Larva", "larva")),
    ("Butterfly2Larvae", ("Butterfly Larva", "larva")),
    ("Butterfly3Larvae", ("Butterfly Larva", "larva")),
    ("Butterfly4Larvae", ("Butterfly Larva", "larva")),
    ("Butterfly6Larvae", ("Butterfly Larva", "larva")),
    ("Butterfly7Larvae", ("Butterfly Larva", "larva")),
    ("Butterfly8Larvae", ("Butterfly Larva", "larva")),
    ("Fish1Eggs", ("Fish Eggs", "larva")),
    # --- Consumables & fuses ---
    ("NitrogenCapsule1", ("Nitrogen Capsule", "consumable")),
    ("MethanCapsule1", ("Methane Capsule", "consumable")),
    ("canister", ("Empty Canister", "consumable")),
    ("Flare", ("Flare", "consumable")),
    ("Explosive", ("Explosive Charge", "consumable")),
    ("FuseEnergy1", ("Energy Fuse", "consumable")),
    ("FuseHeat1", ("Heat Fuse", "consumable")),
    ("FuseOxygen1", ("Oxygen Fuse", "consumable")),
    ("FusePlants1", ("Plants Fuse", "consumable")),
    ("FusePressure1", ("Pressure Fuse", "consumable")),
    ("FuseProduction1", ("Production Fuse", "consumable")),
    ("Optimizer1", ("Optimizer T1", "consumable")),
    ("Optimizer2", ("Optimizer T2", "consumable")),
    ("SpaceMultiplierHeat", ("Heat Space Booster", "consumable")),
    ("SpaceMultiplierInsects", ("Insects Space Booster", "consumable")),
    ("SpaceMultiplierOxygen", ("Oxygen Space Booster", "consumable")),
    ("SpaceMultiplierPlants", ("Plants Space Booster", "consumable")),
    ("SpaceMultiplierPressure", ("Pressure Space Booster", "consumable")),
    # --- Rockets ---
    ("RocketBiomass1", ("Biomass Rocket", "rocket")),
    ("RocketDrones1", ("Drone Rocket", "rocket")),
    ("RocketHeat1", ("Heat Rocket", "rocket")),
    ("RocketInformations1", ("Information Rocket", "rocket")),
    ("RocketInsects1", ("Insects Rocket", "rocket")),
    ("RocketMap1", ("Map Rocket", "rocket")),
    ("RocketMap2", ("Map Rocket", "rocket")),
    ("RocketMap3", ("Map Rocket", "rocket")),
    ("RocketMap4", ("Map Rocket", "rocket")),
    ("RocketOxygen1", ("Oxygen Rocket", "rocket")),
    ("RocketPressure1", ("Pressure Rocket", "rocket")),
    ("RocketReactor", ("Rocket Reactor", "rocket")),
    # --- Terra tokens ---
    ("TerraTokens100", ("100 Terra Tokens", "token")),
    ("TerraTokens500", ("500 Terra Tokens", "token")),
    ("TerraTokens1000", ("1000 Terra Tokens", "token")),
    ("TerraTokens5000", ("5000 Terra Tokens", "token")),
    # --- Chips & blueprints ---
    ("BlueprintT1", ("Blueprint Chip", "chip")),
    ("MapChip", ("Map Chip", "chip")),
    ("Keycard1", ("Keycard", "chip")),
    ("WardenKey", ("Warden Key", "chip")),
    ("WardensChip", ("Warden's Chip", "chip")),
    ("PinChip2", ("Pin Chip", "chip")),
    ("HudChipCleanConstruction", ("Clean Construction Chip", "chip")),
    # --- Storage crates ---
    ("Container1", ("Storage Crate T1", "container")),
    ("Container2", ("Storage Crate T2", "container")),
    ("GoldenContainer", ("Golden Crate", "container")),
    ("ProceduralWreckContainer1", ("Wreck Crate", "container")),
    ("ProceduralWreckContainer2", ("Wreck Crate", "container")),
    ("ProceduralWreckSafe", ("Wreck Safe", "container")),
    # --- Equipment & gear ---
    ("Backpack5", ("Backpack Upgrade", "equipment")),
    ("Jetpack2", ("Jetpack Upgrade", "equipment")),
    ("Jetpack3", ("Jetpack Upgrade", "equipment")),
    ("BootsSpeed1", ("Speed Boots T1", "equipment")),
    ("BootsSpeed2", ("Speed Boots T2", "equipment")),
    ("BootsSpeed3", ("Speed Boots T3", "equipment")),
    ("OxygenTank4", ("Oxygen Tank Upgrade", "equipment")),
    ("HudCompass", ("Compass", "equipment")),
    ("EquipmentIncrease3", ("Equipment Slot Upgrade", "equipment")),
    ("MultiBuild", ("Multi-Build Module", "equipment")),
    ("MultiToolMineSpeed1", ("Mining Speed T1", "equipment")),
    ("MultiToolMineSpeed2", ("Mining Speed T2", "equipment")),
    ("MultiToolMineSpeed3", ("Mining Speed T3", "equipment")),
    ("MultiToolMineSpeed4", ("Mining Speed T4", "equipment")),
    ("MultiToolLight2", ("Tool Light T2", "equipment")),
    ("MultiToolLight3", ("Tool Light T3", "equipment")),
    ("MultiToolDeconstruct2", ("Deconstruct T2", "equipment")),
    ("MultiToolDeconstruct3", ("Deconstruct T3", "equipment")),
    ("Skin-01", ("Suit Skin", "equipment")),
    ("Skin-03", ("Suit Skin", "equipment")),
    ("Skin-05", ("Suit Skin", "equipment")),
    ("Skin-06", ("Suit Skin", "equipment")),
    ("Skin-07", ("Suit Skin", "equipment")),
    ("Skin-09", ("Suit Skin", "equipment")),
    ("Skin-10", ("Suit Skin", "equipment")),
    ("Skin-13", ("Suit Skin", "equipment")),
    ("Skin-14", ("Suit Skin", "equipment")),
    # --- Vehicles & upgrades ---
    ("VehicleTruck", ("Truck", "vehicle")),
    ("VehicleCrafter1", ("Vehicle Crafter", "vehicle")),
    ("VehicleSpeed1", ("Vehicle Speed T1", "vehicle")),
    ("VehicleSpeed2", ("Vehicle Speed T2", "vehicle")),
    ("VehicleSpeed3", ("Vehicle Speed T3", "vehicle")),
    ("VehicleOxygen1", ("Vehicle Oxygen", "vehicle")),
    ("VehicleLights2", ("Vehicle Lights T2", "vehicle")),
    ("VehicleInventorySize1", ("Vehicle Storage T1", "vehicle")),
    ("VehicleInventorySize2", ("Vehicle Storage T2", "vehicle")),
    ("VehicleInventorySize3", ("Vehicle Storage T3", "vehicle")),
    ("VehicleEquipmentSize2", ("Vehicle Equipment T2", "vehicle")),
    ("Drone1", ("Drone", "vehicle")),
    # --- Structures & machines ---
    ("Foundation", ("Foundation", "structure")),
    ("FoundationAngle", ("Angled Foundation", "structure")),
    ("FoundationSlope", ("Sloped Foundation", "structure")),
    ("InteriorStairs1", ("Interior Stairs", "structure")),
    ("WallInside", ("Interior Wall", "structure")),
    ("Fence", ("Fence", "structure")),
    ("Heater1", ("Heater T1", "structure")),
    ("Heater2", ("Heater T2", "structure")),
    ("Heater3", ("Heater T3", "structure")),
    ("Heater4", ("Heater T4", "structure")),
    ("Heater5", ("Heater T5", "structure")),
    ("Drill1", ("Drill T1", "structure")),
    ("Drill2", ("Drill T2", "structure")),
    ("Drill3", ("Drill T3", "structure")),
    ("Drill4", ("Drill T4", "structure")),
    ("OreExtractor1", ("Ore Extractor T1", "structure")),
    ("OreExtractor2", ("Ore Extractor T2", "structure")),
    ("OreExtractor3", ("Ore Extractor T3", "structure")),
    ("GasExtractor2", ("Gas Extractor T2", "structure")),
    ("EnergyGenerator3", ("Energy Generator T3", "structure")),
    ("EnergyGenerator4", ("Energy Generator T4", "structure")),
    ("EnergyGenerator5", ("Energy Generator T5", "structure")),
    ("EnergyGenerator6", ("Energy Generator T6", "structure")),
    ("AlgaeGenerator1", ("Algae Generator T1", "structure")),
    ("AlgaeGenerator2", ("Algae Generator T2", "structure")),
    ("SilkGenerator", ("Silk Generator", "structure")),
    ("biodome", ("Biodome", "structure")),
    ("Biodome2", ("Biodome T2", "structure")),
    ("Biolab", ("Biolab", "structure")),
    ("Ecosystem1", ("Ecosystem Analyzer", "structure")),
    ("Farm1", ("Farm", "structure")),
    ("Faucet1", ("Water Faucet", "structure")),
    ("GrassSpreader1", ("Grass Spreader", "structure")),
    ("SeedSpreader1", ("Seed Spreader T1", "structure")),
    ("SeedSpreader2", ("Seed Spreader T2", "structure")),
    ("TreeSpreader0", ("Tree Spreader T0", "structure")),
    ("TreeSpreader2", ("Tree Spreader T2", "structure")),
    ("VegetableGrower1", ("Vegetable Grower T1", "structure")),
    ("VegetableGrower2", ("Vegetable Grower T2", "structure")),
    ("Vegetube1", ("Vegetube", "structure")),
    ("VegetubeOutside1", ("Outdoor Vegetube", "structure")),
    ("WaterCollector1", ("Water Collector", "structure")),
    ("WaterFilter", ("Water Filter", "structure")),
    ("WaterLifeCollector1", ("Water Life Collector", "structure")),
    ("RecyclingMachine", ("Recycling Machine", "structure")),
    ("AutoCrafter1", ("Auto-Crafter", "structure")),
    ("CraftStation1", ("Craft Station T1", "structure")),
    ("CraftStation2", ("Craft Station T2", "structure")),
    ("CookingStation1", ("Cooking Station", "structure")),
    ("GeneticManipulator1", ("Genetic Manipulator", "structure")),
    ("Incubator1", ("Incubator", "structure")),
    ("LarvaeBase1", ("Larvae Base T1", "structure")),
    ("LarvaeBase3", ("Larvae Base T3", "structure")),
    ("ButterflyDome1", ("Butterfly Dome", "structure")),
    ("ButterflyFarm1", ("Butterfly Farm", "structure")),
    ("Beehive1", ("Beehive", "structure")),
    ("Aquarium1", ("Aquarium T1", "structure")),
    ("Aquarium2", ("Aquarium T2", "structure")),
    ("DroneStation1", ("Drone Station", "structure")),
    ("TradePlatform1", ("Trade Platform", "structure")),
    ("VendingMachine1", ("Vending Machine", "structure")),
    ("Destructor1", ("Destructor", "structure")),
    ("ProceduralInstanceGenerator", ("Anomaly Generator", "structure")),
    ("PlanetViewer1", ("Planet Viewer", "structure")),
    ("Library1", ("Library", "structure")),
    ("Server1", ("Server", "structure")),
    ("ComAntenna", ("Communication Antenna", "structure")),
    ("LaunchPlatform", ("Rocket Launch Platform", "structure")),
    ("EscapePod", ("Escape Pod", "structure")),
    ("pod", ("Habitat Pod", "structure")),
    ("Pod4x", ("Large Habitat Pod", "structure")),
    ("podAngle", ("Angled Habitat Pod", "structure")),
    ("RockExplodable", ("Breakable Rock", "structure")),
    ("wreckpilar", ("Wreck Pillar", "structure")),
    ("WreckServer", ("Wreck Server", "structure")),
    ("WreckFusionGenerator", ("Wreck Fusion Generator", "structure")),
    ("WreckRockExplodable", ("Wreck Breakable Rock", "structure")),
    ("WreckEntryLocked1", ("Locked Wreck Door", "structure")),
    # --- Furniture & decor ---
    ("Chair1", ("Chair", "furniture")),
    ("Chair2", ("Chair", "furniture")),
    ("Table1", ("Table", "furniture")),
    ("TableSmall", ("Small Table", "furniture")),
    ("TableSmall2", ("Small Table", "furniture")),
    ("TableSmall3", ("Small Table", "furniture")),
    ("Sofa", ("Sofa", "furniture")),
    ("SofaAngle", ("Angled Sofa", "furniture")),
    ("SofaColored", ("Sofa", "furniture")),
    ("SofaAngleColored", ("Angled Sofa", "furniture")),
    ("BedDouble", ("Double Bed", "furniture")),
    ("BedDoubleColored", ("Double Bed", "furniture")),
    ("Counter1", ("Counter", "furniture")),
    ("Counter2", ("Counter", "furniture")),
    ("Shelves1", ("Shelves", "furniture")),
    ("Locker1", ("Locker", "furniture")),
    ("FlowerPot2", ("Flower Pot", "furniture")),
    ("Pooltable1", ("Pool Table", "furniture")),
    ("ArcadeMachine1", ("Arcade Machine", "furniture")),
    ("ExerciseBike1", ("Exercise Bike", "furniture")),
    ("Treadmill1", ("Treadmill", "furniture")),
    ("DisplayCase", ("Display Case", "furniture")),
    ("SkinDisplayer", ("Skin Displayer", "furniture")),
    ("Poster1", ("Poster", "furniture")),
    ("Poster9", ("Poster", "furniture")),
    ("InsideLamp1", ("Interior Lamp", "furniture")),
    ("Fridge1", ("Fridge", "furniture")),
    ("Desktop1", ("Desktop Computer", "furniture")),
    ("Desktop2", ("Desktop Computer", "furniture")),
    ("Beacon", ("Beacon", "furniture")),
    ("Vault1", ("Vault", "furniture")),
    ("AnimalEffigie3", ("Animal Effigy", "furniture")),
    ("AnimalEffigie5", ("Animal Effigy", "furniture")),
    ("AnimalEffigie6", ("Animal Effigy", "furniture")),
    ("GoldenEffigie1", ("Golden Effigy", "furniture")),
    ("GoldenEffigie6", ("Golden Effigy", "furniture")),
    ("ScreenBiomass", ("Biomass Screen", "furniture")),
    ("ScreenEnergy", ("Energy Screen", "furniture")),
    ("ScreenMap1", ("Map Screen", "furniture")),
    ("ScreenMessage", ("Message Screen", "furniture")),
    ("ScreenRockets", ("Rockets Screen", "furniture")),
    ("ScreenTerraformation", ("Terraformation Screen", "furniture")),
    ("ScreenTerraStage", ("Terra Stage Screen", "furniture")),
    ("ScreenUnlockables", ("Unlockables Screen", "furniture")),
])


def main():
    out = collections.OrderedDict()
    out["$comment"] = (
        "App-only item catalog keyed by WorldObject.GId. Not part of the save "
        "file. 'icon' on an item overrides its category icon; unknown GIds fall "
        "back to the raw id and the fallbackCategory icon. Regenerate with "
        "tools/item-catalog/gen_catalog.py."
    )
    out["fallbackCategory"] = FALLBACK_CATEGORY
    out["categories"] = CATEGORIES
    items = collections.OrderedDict()
    for gid, (name, cat) in ITEMS.items():
        assert cat in CATEGORIES, f"{gid} -> unknown category {cat}"
        items[gid] = {"displayName": name, "category": cat}
    out["items"] = items

    text = json.dumps(out, indent=2)
    path = "PCEdit.App.Core/Data/ItemCatalog.json"
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text + "\n")
    print(f"wrote {path}: {len(items)} items, {len(CATEGORIES)} categories")


if __name__ == "__main__":
    main()
