#!/usr/bin/env python3
"""Generate PCEdit.App.Core/Data/ItemCatalog.json from a curated mapping.

The GId list was seeded from PCEdit.SaveFileHandler/Standard-2.json (world
objects + unlockedGroups + inventory demand/supply groups). Curate here, then
this script writes the JSON the app embeds. Re-run after editing the tables.
"""
import json
import collections

CATEGORIES = collections.OrderedDict([
    ("ore",        {"displayName": "Ore & Minerals",     "icon": "cat_ore.png"}),
    ("gem",        {"displayName": "Rare Crystals",       "icon": "cat_gem.png"}),
    ("component",  {"displayName": "Crafted Components",  "icon": "cat_component.png"}),
    ("seed",       {"displayName": "Seeds",               "icon": "cat_seed.png"}),
    ("plant",      {"displayName": "Plants & Microbes",   "icon": "cat_plant.png"}),
    ("food",       {"displayName": "Food & Water",        "icon": "cat_food.png"}),
    ("larva",      {"displayName": "Larvae & Eggs",       "icon": "cat_larva.png"}),
    ("structure",  {"displayName": "Structures & Machines","icon": "cat_structure.png"}),
    ("furniture",  {"displayName": "Furniture & Decor",   "icon": "cat_furniture.png"}),
    ("equipment",  {"displayName": "Equipment & Gear",    "icon": "cat_equipment.png"}),
    ("consumable", {"displayName": "Consumables & Fuses", "icon": "cat_consumable.png"}),
    ("rocket",     {"displayName": "Rockets",             "icon": "cat_rocket.png"}),
    ("token",      {"displayName": "Terra Tokens",        "icon": "cat_token.png"}),
    ("chip",       {"displayName": "Chips & Blueprints",  "icon": "cat_chip.png"}),
    ("container",  {"displayName": "Storage Crates",      "icon": "cat_container.png"}),
    ("vehicle",    {"displayName": "Vehicles & Upgrades", "icon": "cat_vehicle.png"}),
    ("misc",       {"displayName": "Miscellaneous",       "icon": "cat_misc.png"}),
])
FALLBACK_CATEGORY = "misc"

# gid -> (displayName, category). Order preserved for readability in the file.
ITEMS = collections.OrderedDict([
    # --- Ore & minerals ---
    ("Iron", ("Iron", "ore")),
    ("Cobalt", ("Cobalt", "ore")),
    ("Titanium", ("Titanium", "ore")),
    ("Aluminium", ("Aluminum", "ore")),
    ("Silicon", ("Silicon", "ore")),
    ("Magnesium", ("Magnesium", "ore")),
    ("Sulfur", ("Sulfur", "ore")),
    ("Iridium", ("Iridium", "ore")),
    ("Osmium", ("Osmium", "ore")),
    ("Uranim", ("Uranium", "ore")),
    ("Zeolite", ("Zeolite", "ore")),
    ("Obsidian", ("Obsidian", "ore")),
    ("ice", ("Ice", "ore")),
    ("Bauxite", ("Bauxite", "ore")),
    ("Dolomite", ("Dolomite", "ore")),
    ("Phosphorus", ("Phosphorus", "ore")),
    ("Selenium", ("Selenium", "ore")),
    ("Uraninite", ("Uraninite", "ore")),
    ("Minable-Tungsten", ("Tungsten", "ore")),
    ("ToxicGoo", ("Toxic Goo", "ore")),
    ("ToxicWater", ("Toxic Water", "ore")),
    ("ToxicSpores", ("Toxic Spores", "ore")),
    ("Toxins", ("Toxins", "ore")),
    ("Amber", ("Amber", "ore")),
    # --- Rare crystals ---
    ("PulsarQuartz", ("Pulsar Quartz", "gem")),
    ("SolarQuartz", ("Solar Quartz", "gem")),
    ("MagnetarQuartz", ("Magnetar Quartz", "gem")),
    ("QuasarQuartz", ("Quasar Quartz", "gem")),
    ("CosmicQuartz", ("Cosmic Quartz", "gem")),
    ("BalzarQuartz", ("Blazar Quartz", "gem")),
    # --- Crafted components ---
    ("Alloy", ("Super Alloy", "component")),
    ("Rod-alloy", ("Super Alloy Rod", "component")),
    ("Rod-iridium", ("Iridium Rod", "component")),
    ("Rod-uranium", ("Uranium Rod", "component")),
    ("CircuitBoard1", ("Circuit Board", "component")),
    ("Bioplastic1", ("Bioplastic Nugget", "component")),
    ("FabricBlue", ("Fabric", "component")),
    ("Silk", ("Silk", "component")),
    ("RedPowder1", ("Explosive Powder", "component")),
    ("Fertilizer1", ("Fertilizer", "component")),
    ("Fertilizer2", ("T2 Fertilizer", "component")),
    ("Mutagen1", ("Mutagen", "component")),
    ("Mutagen2", ("T2 Mutagen", "component")),
    ("FusionEnergyCell", ("Fusion Energy Cell", "component")),
    ("Bacteria1", ("Bacteria Sample", "component")),
    ("Rod-osmium", ("Osmium Rod", "component")),
    ("Rod-tungsten", ("Tungsten Rod", "component")),
    ("Rod-plastic", ("Plastic Rod", "component")),
    ("Fertilizer3", ("T3 Fertilizer", "component")),
    ("Mutagen3", ("T3 Mutagen", "component")),
    ("Mutagen4", ("T4 Mutagen", "component")),
    ("PlasticPolymer", ("Plastic Polymer", "component")),
    ("MicroPlastics", ("Microplastics", "component")),
    ("SmartFabric", ("Smart Fabric", "component")),
    ("SilkWorm", ("Silkworm", "component")),
    ("PurificationGel", ("Purification Gel", "component")),
    ("DNASequence", ("Creature DNA", "component")),
    ("GeneticTrait", ("Genetic Trait", "component")),
    ("TrashMetalsScraps1", ("Metal Scraps", "component")),
    ("TrashMetalsCanisters1", ("Metal Scraps", "component")),
    ("TrashAluminiumScraps1", ("Aluminum Scraps", "component")),
    ("TrashUraniumScraps1", ("Uranium Scraps", "component")),
    ("TrashElectronics1", ("Electronics Scraps", "component")),
    ("AnimalBones", ("Ancient Animal Bones", "component")),
    # --- Seeds ---
    ("Seed0", ("Lirma Seed", "seed")),
    ("Seed1", ("Shanga Seed", "seed")),
    ("Seed2", ("Pestera Seed", "seed")),
    ("Seed3", ("Nulna Seed", "seed")),
    ("Seed4", ("Tuska Seed", "seed")),
    ("Seed6", ("Volnus Plant", "seed")),
    ("Seed7Humble", ("Snepea Seed", "seed")),
    ("Seed8Humble", ("Brelea Seed", "seed")),
    ("SeedGold", ("Golden Seed", "seed")),
    ("Algae1Seed", ("Algae", "seed")),
    ("CookCocoaSeed", ("Cocoa Seed", "seed")),
    ("CookWheatSeed", ("Wheat Seeds", "seed")),
    ("Tree1Seed", ("Linifolia Tree Seed", "seed")),
    ("Tree2Seed", ("Aleatus Tree Seed", "seed")),
    ("Tree8Seed", ("Soleus Tree Seed", "seed")),
    ("Vegetable0Seed", ("Eggplant Seeds", "seed")),
    ("Vegetable1Seed", ("Squash Seeds", "seed")),
    ("Vegetable2Seed", ("Bean Seeds", "seed")),
    ("Vegetable3Seed", ("Mushroom Seeds", "seed")),
    ("Seed5", ("Orema Plant", "seed")),
    ("Seed9Humble", ("Seleus Seed", "seed")),
    ("Seed10Humble", ("Furteo Seed", "seed")),
    ("Seed11Humble", ("Humblea Seed", "seed")),
    ("Tree0Seed", ("Iterra Tree Seed", "seed")),
    ("Tree9Seed", ("Shreox Tree Seed", "seed")),
    ("Tree10Seed", ("Rosea Tree Seed", "seed")),
    ("Tree13Seed", ("Ruberu Tree Seed", "seed")),
    ("Tree16Seed", ("Pamelia Tree Seed", "seed")),
    # --- Plants & microbes ---
    ("Vegetable0Growable", ("Eggplant", "plant")),
    ("Vegetable1Growable", ("Squash", "plant")),
    ("Vegetable2Growable", ("Beans", "plant")),
    ("Vegetable3Growable", ("Mushroom", "plant")),
    ("TreeRoot", ("Tree Bark", "plant")),
    ("Phytoplankton1", ("Phytoplankton", "plant")),
    ("Phytoplankton2", ("Phytoplankton B", "plant")),
    ("Phytoplankton3", ("Phytoplankton C", "plant")),
    ("CookCocoaGrowable", ("Cocoa", "plant")),
    ("CookWheatGrowable", ("Wheat", "plant")),
    ("Ivy1", ("Ivy", "plant")),
    ("PristineMushroom", ("Pristine Mushroom", "plant")),
    # --- Food & water ---
    ("astrofood", ("Space Food", "food")),
    ("honey", ("Honey", "food")),
    ("WaterBottle1", ("Water Bottle", "food")),
    ("astrofood2", ("High Quality Food", "food")),
    ("CookCake1", ("Birthday Cake", "food")),
    ("PurifiedWater", ("Purified Water", "food")),
    # --- Larvae & eggs ---
    ("Bee1Larvae", ("Bee Larva", "larva")),
    ("Butterfly1Larvae", ("Azurae Butterfly Larva", "larva")),
    ("Butterfly2Larvae", ("Leani Butterfly Larva", "larva")),
    ("Butterfly3Larvae", ("Fensea Butterfly Larva", "larva")),
    ("Butterfly4Larvae", ("Galaxe Butterfly Larva", "larva")),
    ("Butterfly6Larvae", ("Empalio Butterfly Larva", "larva")),
    ("Butterfly7Larvae", ("Penga Butterfly Larva", "larva")),
    ("Butterfly8Larvae", ("Chevrone Butterfly Larva", "larva")),
    ("Fish1Eggs", ("Provios Fish Eggs", "larva")),
    ("Butterfly5Larvae", ("Abstreus Butterfly Larva", "larva")),
    ("Butterfly9Larvae", ("Aemel Butterfly Larva", "larva")),
    ("Butterfly11Larvae", ("Nere Butterfly Larva", "larva")),
    ("Butterfly15Larvae", ("Futura Butterfly Larva", "larva")),
    ("Butterfly16Larvae", ("Imeo Butterfly Larva", "larva")),
    ("Butterfly17Larvae", ("Serena Butterfly Larva", "larva")),
    ("Butterfly18Larvae", ("Golden Butterfly Larva", "larva")),
    ("Fish3Eggs", ("Gerrero Fish Eggs", "larva")),
    ("Fish5Eggs", ("Ulani Fish Eggs", "larva")),
    ("Fish6Eggs", ("Aelera Fish Eggs", "larva")),
    ("Frog1Eggs", ("Generic Frog Eggs", "larva")),
    ("Frog2Eggs", ("Huli Frog Eggs", "larva")),
    ("Frog8Eggs", ("Cillus Frog Eggs", "larva")),
    ("Frog9Eggs", ("Amedo Frog Eggs", "larva")),
    ("Frog10Eggs", ("Kenjoss Frog Eggs", "larva")),
    ("Frog12Eggs", ("Leglus Frog Eggs", "larva")),
    # --- Consumables & fuses ---
    ("NitrogenCapsule1", ("Nitrogen Cartridge", "consumable")),
    ("MethanCapsule1", ("Methane Cartridge", "consumable")),
    ("canister", ("Canister", "consumable")),
    ("Flare", ("Flare", "consumable")),
    ("Explosive", ("Explosive", "consumable")),
    ("FuseEnergy1", ("Energy Multiplier Fuse", "consumable")),
    ("FuseHeat1", ("Heat Multiplier Fuse", "consumable")),
    ("FuseOxygen1", ("Oxygen Multiplier Fuse", "consumable")),
    ("FusePlants1", ("Plant Multiplier Fuse", "consumable")),
    ("FusePressure1", ("Pressure Multiplier Fuse", "consumable")),
    ("FuseProduction1", ("Production Multiplier Fuse", "consumable")),
    ("Optimizer1", ("Machine Optimizer", "consumable")),
    ("Optimizer2", ("T2 Machine Optimizer", "consumable")),
    ("SpaceMultiplierHeat", ("Space Heat Multiplier", "consumable")),
    ("SpaceMultiplierInsects", ("Insects Space Booster", "consumable")),
    ("SpaceMultiplierOxygen", ("Space Oxygen Multiplier", "consumable")),
    ("SpaceMultiplierPlants", ("Plants Space Booster", "consumable")),
    ("SpaceMultiplierPressure", ("Space Pressure Multiplier", "consumable")),
    ("OxygenCapsule1", ("Oxygen Capsule", "consumable")),
    ("ChlorineCapsule1", ("Chlorine Dioxide", "consumable")),
    ("PurificationCapsule", ("Purification Capsule", "consumable")),
    ("AntiToxinsExplosive1", ("T1 Toxic Goo Removal Explosives", "consumable")),
    ("FuseAnimals1", ("Animals Multiplier Fuse", "consumable")),
    ("FuseGrowth1", ("Growth Multiplier Fuse", "consumable")),
    ("FusePurification1", ("Purification Multiplier Fuse", "consumable")),
    ("FuseTradeRocketsSpeed1", ("Trade Rocket Multiplier Fuse", "consumable")),
    ("FuseCartridge", ("Fuse Cartridge", "consumable")),
    ("SpaceMultiplierAnimals", ("Animals Space Booster", "consumable")),
    ("AnimalFood1", ("T1 Animal Food", "consumable")),
    ("AnimalFood2", ("T2 Animal Food", "consumable")),
    # --- Rockets ---
    ("RocketBiomass1", ("Plant Rocket", "rocket")),
    ("RocketDrones1", ("Drone Visualization Rocket", "rocket")),
    ("RocketHeat1", ("Asteroid Attraction Rocket", "rocket")),
    ("RocketInformations1", ("Map Information Rocket", "rocket")),
    ("RocketInsects1", ("Insect Spreader Rocket", "rocket")),
    ("RocketMap1", ("T1 GPS Satellite", "rocket")),
    ("RocketMap2", ("T2 GPS Satellite", "rocket")),
    ("RocketMap3", ("T3 GPS Satellite", "rocket")),
    ("RocketMap4", ("T4 GPS Satellite", "rocket")),
    ("RocketOxygen1", ("Seed Spreader Rocket", "rocket")),
    ("RocketPressure1", ("Magnetic Field Protection Rocket", "rocket")),
    ("RocketReactor", ("Rocket Engine", "rocket")),
    ("RocketAnimals1", ("Animals Spreader Rocket", "rocket")),
    ("RocketBiomass2", ("T2 Plant Rocket", "rocket")),
    ("RocketInformations2", ("T2 Map Information Rocket", "rocket")),
    ("RocketInsects2", ("T2 Insect Spreader Rocket", "rocket")),
    ("RocketPressure2", ("T2 Magnetic Field Protection Rocket", "rocket")),
    ("RocketReactor2", ("T2 Rocket Engine", "rocket")),
    ("RocketTravel1", ("Interplanetary Travel Rocket", "rocket")),
    # --- Terra tokens ---
    ("TerraTokens100", ("Terra Tokens: 100", "token")),
    ("TerraTokens500", ("Terra Tokens: 500", "token")),
    ("TerraTokens1000", ("Terra Tokens: 1000", "token")),
    ("TerraTokens5000", ("Terra Tokens: 5000", "token")),
    # --- Chips & blueprints ---
    ("BlueprintT1", ("Blueprint Microchip", "chip")),
    ("MapChip", ("Microchip - Map", "chip")),
    ("Keycard1", ("Access Card", "chip")),
    ("WardenKey", ("Warden's Key", "chip")),
    ("WardensChip", ("Warden Key Detector", "chip")),
    ("PinChip2", ("Microchip - T2 Blueprint Pinning", "chip")),
    ("HudChipCleanConstruction", ("Microchip - Construction Menu Filter", "chip")),
    ("KeyCard2", ("Access Card", "chip")),
    ("PinChip3", ("Microchip - T3 Blueprint Pinning", "chip")),
    ("BlueprintSolarQuartz", ("Solar Quartz Blueprint", "chip")),
    ("BlueprintEquipmentIncrease1", ("Equipment Capacity T1", "chip")),
    ("BlueprintEquipmentIncrease2", ("Equipment Capacity T2", "chip")),
    ("BlueprintEquipmentIncrease3", ("Equipment Capacity T3", "chip")),
    ("BlueprintEquipmentIncrease4", ("Equipment Capacity T4", "chip")),
    ("BlueprintEquipmentIncrease5", ("Equipment Capacity T5", "chip")),
    ("ToxicZoneHudDisplayer2", ("Microchip - T2 Toxic Areas Informations", "chip")),
    # --- Storage crates ---
    ("Container1", ("Storage Crate", "container")),
    ("Container2", ("Locker Storage", "container")),
    ("GoldenContainer", ("Golden Crate", "container")),
    ("ProceduralWreckContainer1", ("Storage Crate", "container")),
    ("ProceduralWreckContainer2", ("Storage Crate", "container")),
    ("ProceduralWreckSafe", ("Big Safe", "container")),
    ("Container3", ("T2 Locker Storage", "container")),
    ("ContainerAqualis", ("Clam", "container")),
    ("ContainerToxic1", ("Toxic Goo Storage", "container")),
    # --- Equipment & gear ---
    ("Backpack5", ("T5 Backpack", "equipment")),
    ("Backpack6", ("T6 Backpack", "equipment")),
    ("Jetpack2", ("T2 Jetpack", "equipment")),
    ("Jetpack3", ("T3 Jetpack", "equipment")),
    ("BootsSpeed1", ("T1 Agility Boots", "equipment")),
    ("BootsSpeed2", ("T2 Agility Boots", "equipment")),
    ("BootsSpeed3", ("T3 Agility Boots", "equipment")),
    ("OxygenTank4", ("T4 Oxygen Tank", "equipment")),
    ("HudCompass", ("Microchip - Compass", "equipment")),
    ("EquipmentIncrease3", ("T3 Exoskeleton", "equipment")),
    ("MultiBuild", ("Microchip - Construction", "equipment")),
    ("MultiToolMineSpeed1", ("Microchip - T1 Mining Speed", "equipment")),
    ("MultiToolMineSpeed2", ("Microchip - T2 Mining Speed", "equipment")),
    ("MultiToolMineSpeed3", ("Microchip - T3 Mining Speed", "equipment")),
    ("MultiToolMineSpeed4", ("Microchip - T4 Mining Speed", "equipment")),
    ("MultiToolLight2", ("Microchip - T2 Torch", "equipment")),
    ("MultiToolLight3", ("Microchip - T3 Torch", "equipment")),
    ("MultiToolDeconstruct2", ("Microchip - T2 Deconstruction", "equipment")),
    ("MultiToolDeconstruct3", ("Microchip - T3 Deconstruction", "equipment")),
    ("Skin-01", ("Spacesuit Comto", "equipment")),
    ("Skin-03", ("Spacesuit Primo", "equipment")),
    ("Skin-05", ("Spacesuit Scifo", "equipment")),
    ("Skin-06", ("Spacesuit Cipto", "equipment")),
    ("Skin-07", ("Spacesuit Beteo", "equipment")),
    ("Skin-09", ("Spacesuit Fablo", "equipment")),
    ("Skin-10", ("Spacesuit Tubio", "equipment")),
    ("Skin-13", ("Spacesuit Mekio", "equipment")),
    ("Skin-14", ("Spacesuit Abyso", "equipment")),
    ("Backpack1", ("T1 Backpack", "equipment")),
    ("Backpack2", ("T2 Backpack", "equipment")),
    ("Backpack3", ("T3 Backpack", "equipment")),
    ("Backpack4", ("T4 Backpack", "equipment")),
    ("Backpack7", ("T7 Backpack", "equipment")),
    ("Jetpack1", ("T1 Jetpack", "equipment")),
    ("Jetpack4", ("T4 Jetpack", "equipment")),
    ("OxygenTank2", ("T2 Oxygen Tank", "equipment")),
    ("EquipmentIncrease1", ("T1 Exoskeleton", "equipment")),
    ("EquipmentIncrease2", ("T2 Exoskeleton", "equipment")),
    ("EquipmentIncrease4", ("T4 Exoskeleton", "equipment")),
    ("EquipmentIncrease5", ("T5 Exoskeleton", "equipment")),
    ("MultiDeconstruct", ("Microchip - Deconstruction", "equipment")),
    ("MultiToolLight", ("Microchip - Torch", "equipment")),
    ("MultiToolCleaningGooChip2", ("Microchip - T2 Goo Cleaning", "equipment")),
    ("Skin-02", ("Spacesuit Blasto", "equipment")),
    ("Skin-15", ("Spacesuit Ettio", "equipment")),
    ("Skin-16", ("Spacesuit Plesao", "equipment")),
    ("Skin-17", ("Spacesuit Rorao", "equipment")),
    ("Skin-21", ("Spacesuit Sunsio", "equipment")),
    # --- Vehicles & upgrades ---
    ("VehicleTruck", ("Vehicle - Rover", "vehicle")),
    ("VehicleCrafter1", ("Vehicle Station", "vehicle")),
    ("VehicleSpeed1", ("Vehicle - T1 Speed Increase", "vehicle")),
    ("VehicleSpeed2", ("Vehicle - T2 Speed Increase", "vehicle")),
    ("VehicleSpeed3", ("Vehicle - T3 Speed Increase", "vehicle")),
    ("VehicleOxygen1", ("Vehicle - Unlimited Oxygen", "vehicle")),
    ("VehicleLights2", ("Vehicle - T2 Lights", "vehicle")),
    ("VehicleInventorySize1", ("Vehicle - T1 Inventory Increase", "vehicle")),
    ("VehicleInventorySize2", ("Vehicle - T2 Inventory Increase", "vehicle")),
    ("VehicleInventorySize3", ("Vehicle - T3 Inventory Increase", "vehicle")),
    ("VehicleEquipmentSize2", ("Vehicle - T2 Equipment Increase", "vehicle")),
    ("Drone1", ("T1 Drone", "vehicle")),
    ("Drone2", ("T2 Drone", "vehicle")),
    ("Drone3", ("T3 Drone", "vehicle")),
    ("DroneLog", ("Drone's Log", "vehicle")),
    ("VehicleBeacon1", ("Vehicle - Beacon", "vehicle")),
    ("VehicleJetpack1", ("Jetpack for Vehicle", "vehicle")),
    ("VehicleLights1", ("Vehicle - T1 Lights", "vehicle")),
    ("VehicleLogistic1", ("Vehicle - Logistics", "vehicle")),
    # --- Structures & machines ---
    ("Foundation", ("Foundation Grid", "structure")),
    ("FoundationAngle", ("Foundation - Angle", "structure")),
    ("FoundationSlope", ("Foundation - Slope", "structure")),
    ("InteriorStairs1", ("Interior Stairs", "structure")),
    ("WallInside", ("Interior Wall", "structure")),
    ("Fence", ("Fence", "structure")),
    ("Heater1", ("T1 Heater", "structure")),
    ("Heater2", ("T2 Heater", "structure")),
    ("Heater3", ("T3 Heater", "structure")),
    ("Heater4", ("T4 Heater", "structure")),
    ("Heater5", ("T5 Heater", "structure")),
    ("Drill1", ("T2 Drill", "structure")),
    ("Drill2", ("T3 Drill", "structure")),
    ("Drill3", ("T4 Drill", "structure")),
    ("Drill4", ("T5 Drill", "structure")),
    ("OreExtractor1", ("Ore Extractor", "structure")),
    ("OreExtractor2", ("T2 Ore Extractor", "structure")),
    ("OreExtractor3", ("T3 Ore Extractor", "structure")),
    ("GasExtractor2", ("T2 Gas Extractor", "structure")),
    ("EnergyGenerator3", ("T2 Solar Panel", "structure")),
    ("EnergyGenerator4", ("T1 Nuclear Reactor", "structure")),
    ("EnergyGenerator5", ("T2 Nuclear Reactor", "structure")),
    ("EnergyGenerator6", ("Nuclear Fusion Generator", "structure")),
    ("AlgaeGenerator1", ("T1 Algae Generator", "structure")),
    ("AlgaeGenerator2", ("T2 Algae Generator", "structure")),
    ("SilkGenerator", ("Silk Generator", "structure")),
    ("biodome", ("Biodome", "structure")),
    ("Biodome2", ("T2 Biodome", "structure")),
    ("Biolab", ("Biolab", "structure")),
    ("Ecosystem1", ("Ecosystem", "structure")),
    ("Farm1", ("Outdoor Farm", "structure")),
    ("Faucet1", ("Faucet", "structure")),
    ("GrassSpreader1", ("Grass Spreader", "structure")),
    ("SeedSpreader1", ("Flower Spreader", "structure")),
    ("SeedSpreader2", ("T2 Flower Spreader", "structure")),
    ("TreeSpreader0", ("Tree Spreader", "structure")),
    ("TreeSpreader2", ("T3 Tree Spreader", "structure")),
    ("VegetableGrower1", ("Food Grower", "structure")),
    ("VegetableGrower2", ("T2 Food Grower", "structure")),
    ("Vegetube1", ("T1 Vegetube", "structure")),
    ("VegetubeOutside1", ("T3 Vegetube", "structure")),
    ("WaterCollector1", ("Atmospheric Water Collector", "structure")),
    ("WaterFilter", ("Water Filter", "structure")),
    ("WaterLifeCollector1", ("Water Life Collector", "structure")),
    ("RecyclingMachine", ("Recycling Machine", "structure")),
    ("AutoCrafter1", ("Auto-Crafter", "structure")),
    ("CraftStation1", ("T2 Craft Station", "structure")),
    ("CraftStation2", ("Advanced Craft Station", "structure")),
    ("CookingStation1", ("Cooking Station", "structure")),
    ("GeneticManipulator1", ("Tree Seed Sequencer", "structure")),
    ("Incubator1", ("Incubator", "structure")),
    ("LarvaeBase1", ("Common Larva", "structure")),
    ("LarvaeBase3", ("Rare Larva", "structure")),
    ("ButterflyDome1", ("Butterfly Dome", "structure")),
    ("ButterflyFarm1", ("Butterfly Farm", "structure")),
    ("Beehive1", ("Beehive", "structure")),
    ("Aquarium1", ("T1 Aquarium", "structure")),
    ("Aquarium2", ("T2 Aquarium", "structure")),
    ("DroneStation1", ("Drone Station", "structure")),
    ("TradePlatform1", ("Trade Space Rocket", "structure")),
    ("VendingMachine1", ("Vending Machine", "structure")),
    ("Destructor1", ("Shredder Machine", "structure")),
    ("ProceduralInstanceGenerator", ("Anomaly Generator", "structure")),
    ("PlanetViewer1", ("Planet Viewer", "structure")),
    ("Library1", ("Library", "structure")),
    ("Server1", ("Server", "structure")),
    ("ComAntenna", ("Communication Antenna", "structure")),
    ("LaunchPlatform", ("Launch Platform", "structure")),
    ("EscapePod", ("Escape Pod", "structure")),
    ("pod", ("Living Compartment", "structure")),
    ("Pod4x", ("Big Living Compartment", "structure")),
    ("podAngle", ("Living Compartment Corner", "structure")),
    ("RockExplodable", ("Breakable Rock", "structure")),
    ("wreckpilar", ("Debris", "structure")),
    ("WreckServer", ("Technical Debris", "structure")),
    ("WreckFusionGenerator", ("Fusion Reactor", "structure")),
    ("WreckRockExplodable", ("Wreck Breakable Rock", "structure")),
    ("WreckEntryLocked1", ("Access Console", "structure")),
    ("Drill0", ("T1 Drill", "structure")),
    ("GasExtractor1", ("Gas Extractor", "structure")),
    ("OreBreaker2", ("T2 Ore Crusher", "structure")),
    ("OreBreaker3", ("T3 Ore Crusher", "structure")),
    ("EnergyGenerator1", ("Wind Turbine", "structure")),
    ("EnergyGenerator2", ("T1 Solar Panel", "structure")),
    ("WindTurbine1", ("T2 Wind Turbine", "structure")),
    ("AirFilter1", ("Air Filter", "structure")),
    ("AirPurificationMachine1", ("T1 Atmosphere Purifier", "structure")),
    ("AirPurificationMachine2", ("T2 Atmosphere Purifier", "structure")),
    ("AirPurificationMachine3", ("T3 Atmosphere Purifier", "structure")),
    ("AirPurificationMachine4", ("T4 Atmosphere Purifier", "structure")),
    ("DetoxificationMachine2", ("T2 Detoxification Machine", "structure")),
    ("ToxinsFilter2", ("T2 Toxins Filter", "structure")),
    ("ToxicWaterCollector1", ("T1 Toxic Water Collector", "structure")),
    ("ToxicWaterCollector2", ("T2 Toxic Water Collector", "structure")),
    ("WaterCollector2", ("Lake Water Collector", "structure")),
    ("Farm2", ("T2 Outdoor Farm", "structure")),
    ("Vegetube2", ("T2 Vegetube", "structure")),
    ("TreeSpreader1", ("T2 Tree Spreader", "structure")),
    ("TreePlanter2", ("Bonzaï Pot", "structure")),
    ("AmphibiansFarm1", ("Amphibian Farm", "structure")),
    ("FishFarm1", ("Fish Farm", "structure")),
    ("AquariumTube1", ("Aquarium Tube", "structure")),
    ("ButterflyFarm2", ("T2 Butterfly Farm", "structure")),
    ("ButterflyDisplayer1", ("Butterfly Display Box", "structure")),
    ("Beehive2", ("T2 Beehive", "structure")),
    ("AnimalShelter1", ("Animal Shelter", "structure")),
    ("AnimalFeeder1", ("Animal Feeder", "structure")),
    ("LarvaeBase2", ("Uncommon Larva", "structure")),
    ("GeneticExtractor1", ("Genetic Extractor", "structure")),
    ("GeneticSynthetizer1", ("Genetic Synthesizer", "structure")),
    ("QuartzCraftStation1", ("Quartz Craft Station", "structure")),
    ("ToxicRefinementCraftStation1", ("Craft Station - Refinement", "structure")),
    ("RecyclingMachine2", ("T2 Recycling Machine", "structure")),
    ("HarvestingRobot1", ("Harvesting Robot", "structure")),
    ("InterplanetaryExchangePlatform1", ("Interplanetary Exchange Shuttle", "structure")),
    ("DeparturePlatform", ("Extraction Platform", "structure")),
    ("Teleporter1", ("Teleporter", "structure")),
    ("PortalGenerator1", ("Portal Generator", "structure")),
    ("HologramGenerator", ("Hologram Projector", "structure")),
    ("EscapePodHumble", ("Escape Pod (Humble)", "structure")),
    ("EscapePodToxicity", ("Escape Pod (Toxicity)", "structure")),
    ("EscapePodInterplanetary", ("Interplanetary Escape Pod", "structure")),
    ("Pod9xA", ("Rounded Living Compartment", "structure")),
    ("Pod9xB", ("Living Compartment with Dome", "structure")),
    ("Pod9xC", ("3x3 Living Compartment", "structure")),
    ("Elevator", ("Elevator", "structure")),
    ("Stairs", ("Outdoor Stairs", "structure")),
    ("WallWaterLife", ("Aquatic Life Wall", "structure")),
    ("GenerationGroupVein", ("Resource Vein", "structure")),
    ("WreckEntryLocked2", ("Access Console", "structure")),
    ("EndingExplosives", ("Large Explosive Device", "structure")),
    # --- Furniture & decor ---
    ("Chair1", ("Chair", "furniture")),
    ("Chair2", ("Cozy Chair", "furniture")),
    ("Table1", ("Big Table", "furniture")),
    ("TableSmall", ("Table", "furniture")),
    ("TableSmall2", ("Small Table", "furniture")),
    ("TableSmall3", ("Glass Table", "furniture")),
    ("Sofa", ("Sofa", "furniture")),
    ("SofaAngle", ("Corner Sofa", "furniture")),
    ("SofaColored", ("Customizable Sofa", "furniture")),
    ("SofaAngleColored", ("Customizable Corner Sofa", "furniture")),
    ("BedDouble", ("Double Bed", "furniture")),
    ("BedDoubleColored", ("Customizable Bed", "furniture")),
    ("Counter1", ("Countertop", "furniture")),
    ("Counter2", ("Countertop", "furniture")),
    ("Shelves1", ("Shelves", "furniture")),
    ("Locker1", ("Locker", "furniture")),
    ("FlowerPot2", ("Hanging Flower Pot", "furniture")),
    ("Pooltable1", ("Pool Table", "furniture")),
    ("ArcadeMachine1", ("Arcade Machine", "furniture")),
    ("ExerciseBike1", ("Indoor Bike", "furniture")),
    ("Treadmill1", ("Treadmill", "furniture")),
    ("DisplayCase", ("Display Case", "furniture")),
    ("SkinDisplayer", ("Spacesuit Displayer", "furniture")),
    ("Poster1", ("Poster A", "furniture")),
    ("Poster3", ("Poster C", "furniture")),
    ("Poster9", ("Poster I", "furniture")),
    ("LavaLamp1", ("Lava Lamp", "furniture")),
    ("InsideLamp1", ("Area Lamp", "furniture")),
    ("Fridge1", ("Fridge", "furniture")),
    ("Desktop1", ("Desktop", "furniture")),
    ("Desktop2", ("Desktop", "furniture")),
    ("Beacon", ("Beacon", "furniture")),
    ("Vault1", ("Safe Vault", "furniture")),
    ("AnimalEffigie3", ("Animal Effigy : Tilopina", "furniture")),
    ("AnimalEffigie4", ("Animal Effigy : Snoober", "furniture")),
    ("AnimalEffigie5", ("Animal Effigy : Muthus", "furniture")),
    ("AnimalEffigie6", ("Animal Effigy : Hydrequus", "furniture")),
    ("AnimalEffigie7", ("Animal Effigy : Arbatillo", "furniture")),
    ("GoldenEffigie1", ("Golden Effigy", "furniture")),
    ("GoldenEffigie6", ("Golden Effigy", "furniture")),
    ("ScreenBiomass", ("Biomass Screen", "furniture")),
    ("ScreenEnergy", ("Screen - Energy Levels", "furniture")),
    ("ScreenMap1", ("Screen - Mapping", "furniture")),
    ("ScreenMessage", ("Screen - Transmissions", "furniture")),
    ("ScreenRockets", ("Screen - Orbital Information", "furniture")),
    ("ScreenTerraformation", ("Screen - Terraformation", "furniture")),
    ("ScreenTerraStage", ("Screen - Progress", "furniture")),
    ("ScreenUnlockables", ("Screen - Blueprints", "furniture")),
    ("AnimalEffigie1", ("Animal Effigy : Sharky", "furniture")),
    ("AnimalEffigie2", ("Animal Effigy : Allyca", "furniture")),
    ("AnimalEffigie8", ("Animal Effigy : Carachnid", "furniture")),
    ("AnimalEffigie9", ("Animal Effigy : Doggox", "furniture")),
    ("GoldenEffigie2", ("Golden Effigy", "furniture")),
    ("GoldenEffigie4", ("Golden Effigy", "furniture")),
    ("GoldenEffigie5", ("Golden Effigy", "furniture")),
    ("GoldenToxicityEffigie6", ("Golden Effigy", "furniture")),
    ("StarformEffigie3", ("Starform Effigy", "furniture")),
    ("ToxicityDiorama1", ("Terraforming Diorama A", "furniture")),
    ("FlowerPot3", ("Big Flower Pot", "furniture")),
    ("FountainBig", ("Fountain", "furniture")),
    ("Poster2", ("Poster B", "furniture")),
    ("Poster4", ("Poster D", "furniture")),
    ("Poster5", ("Poster E", "furniture")),
    ("Poster7", ("Poster G", "furniture")),
    ("Poster8", ("Poster H", "furniture")),
    ("Poster10", ("Poster J", "furniture")),
    ("Sign", ("Sign", "furniture")),
    ("Toilet1", ("Toilet", "furniture")),
    ("Shower1", ("Shower", "furniture")),
    ("Trashcan1", ("Trash Can", "furniture")),
    ("ScreenSystem1", ("Solar System Screen", "furniture")),
    ("ScreenToxic1", ("Screen - Toxicity", "furniture")),
    # --- Items previously known only as logistics groups ---
    ("AnimalFood3", ("T3 Animal Food", "consumable")),
    ("AntiToxinsExplosive2", ("T2 Toxic Goo Removal Explosives", "consumable")),
    ("Butterfly10Larvae", ("Liux Butterfly Larva", "larva")),
    ("Butterfly12Larvae", ("Lorpen Butterfly Larva", "larva")),
    ("Butterfly13Larvae", ("Fiorente Butterfly Larva", "larva")),
    ("Butterfly14Larvae", ("Alben Butterfly Larva", "larva")),
    ("Butterfly19Larvae", ("Faleria Butterfly Larva", "larva")),
    ("Butterfly20Larvae", ("Oesbe Butterfly Larva", "larva")),
    ("Butterfly21Larvae", ("Lucia Butterfly Larva", "larva")),
    ("CookChocolate", ("Chocolate", "food")),
    ("CookCookie1", ("Cookie", "food")),
    ("CookCroissant", ("Croissant", "food")),
    ("CookFlour", ("Flour", "food")),
    ("CookStew1", ("Honey Cooked Beans", "food")),
    ("CookStewFish1", ("Fish Soup", "food")),
    ("Fish2Eggs", ("Vilnus Fish Eggs", "larva")),
    ("Fish4Eggs", ("Khrom Fish Eggs", "larva")),
    ("Fish7Eggs", ("Tegede Fish Eggs", "larva")),
    ("Fish8Eggs", ("Ecaru Fish Eggs", "larva")),
    ("Fish9Eggs", ("Buyu Fish Eggs", "larva")),
    ("Fish10Eggs", ("Tiloo Fish Eggs", "larva")),
    ("Fish11Eggs", ("Golden Fish Eggs", "larva")),
    ("Fish12Eggs", ("Velkia Fish Eggs", "larva")),
    ("Fish13Eggs", ("Galbea Fish Eggs", "larva")),
    ("Fish14Eggs", ("Stabu Fish Eggs", "larva")),
    ("Fish15Eggs", ("Atabu Fish Eggs", "larva")),
    ("Frog3Eggs", ("Felicianna Frog Eggs", "larva")),
    ("Frog4Eggs", ("Strabo Frog Eggs", "larva")),
    ("Frog5Eggs", ("Trajuu Frog Eggs", "larva")),
    ("Frog6Eggs", ("Aiolus Frog Eggs", "larva")),
    ("Frog7Eggs", ("Afae Frog Eggs", "larva")),
    ("Frog11Eggs", ("Lavaum Frog Eggs", "larva")),
    ("Frog13Eggs", ("Jumi Frog Eggs", "larva")),
    ("Frog14Eggs", ("Seren Frog Eggs", "larva")),
    ("Frog15Eggs", ("Acuzzi Frog Eggs", "larva")),
    ("Frog16Eggs", ("Toxifia Frog Eggs", "larva")),
    ("FrogGoldEggs", ("Golden Frog Eggs", "larva")),
    ("FuseInsects1", ("Insects Multiplier Fuse", "consumable")),
    ("ToxicityAmmo", ("Toxic Artillery Shell", "consumable")),
    ("ToxicityAmmoPack", ("Toxic Artillery Shells Pack", "consumable")),
    ("ToxicityMedecine", ("Pristine Purifying Balm", "consumable")),
    ("ToxicityMedecinePack", ("Pristine Purifying Balms Pack", "consumable")),
    ("Tree3Seed", ("Cernea Tree Seed", "seed")),
    ("Tree4Seed", ("Elegea Tree Seed", "seed")),
    ("Tree5Seed", ("Humelora Tree Seed", "seed")),
    ("Tree6Seed", ("Aemora Tree Seed", "seed")),
    ("Tree7Seed", ("Pleom Tree Seed", "seed")),
    ("Tree11Seed", ("Lillia Tree Seed", "seed")),
    ("Tree12Seed", ("Prunea Tree Seed", "seed")),
    ("Tree14Seed", ("Malissea Tree Seed", "seed")),
    ("Tree15Seed", ("Redwo Tree Seed", "seed")),
    ("Tree17Seed", ("Detoxo Tree Seed", "seed")),
    ("Tree18Seed", ("Brojo Tree Seed", "seed")),
    # --- Newly discovered via planetcrafter.th.gl ---
    ("AnimalEffigie10", ("Animal Effigy : Smilorex", "furniture")),
    ("Arch1", ("Metal Arch", "structure")),
    ("BedSimple", ("Bed", "furniture")),
    ("Butterfly13Hatched", ("Constela Butterfly Larva", "larva")),
    ("ButterflyFarm3", ("T3 Butterfly Farm", "structure")),
    ("ContainerGoldenAqualis", ("Golden Clam", "container")),
    ("DebrisContainer1", ("Container from Space", "container")),
    ("DetoxificationMachine1", ("T1 Detoxification Machine", "structure")),
    ("DetoxificationMachine3", ("T3 Detoxification Machine", "structure")),
    ("FenceRounded", ("Rounded Fence", "structure")),
    ("Fireplace", ("Fireplace", "furniture")),
    ("FishDisplayer1", ("Fish Display", "structure")),
    ("FishFarm2", ("T2 Fish Farm", "structure")),
    ("FloorAngleGlass", ("Rounded Glass Floor", "structure")),
    ("FloorGlass", ("Living Compartment Glass", "structure")),
    ("FlowerPot1", ("Flower Pot", "furniture")),
    ("FrogDisplayer1", ("Frog Displayer", "structure")),
    ("FusionGenerator1", ("Fusion Reactor", "structure")),
    ("GoldenEffigie3", ("Golden Effigy", "furniture")),
    ("GoldenEffigie7", ("Golden Effigy", "furniture")),
    ("GoldenEffigie8", ("Golden Effigy", "furniture")),
    ("GoldenEffigie9", ("Golden Effigy", "furniture")),
    ("GoldenToxicityEffigie1", ("Golden Effigy", "furniture")),
    ("GoldenToxicityEffigie2", ("Golden Effigy", "furniture")),
    ("GoldenToxicityEffigie3", ("Golden Effigy", "furniture")),
    ("GoldenToxicityEffigie4", ("Golden Effigy", "furniture")),
    ("GoldenToxicityEffigie5", ("Golden Effigy", "furniture")),
    ("Incubator2", ("T2 Incubator", "structure")),
    ("InsideLamp2", ("Intense Area Lamp", "furniture")),
    ("Jetpack5", ("T5 Jetpack", "equipment")),
    ("Ladder", ("Indoor Ladder", "structure")),
    ("LightBoxMedium", ("Light Box", "furniture")),
    ("Megadome1", ("Megadome", "structure")),
    ("MultiToolCleaningGooChip1", ("Microchip - T1 Goo Cleaning", "equipment")),
    ("MultiToolCleaningGooChip3", ("Microchip - T3 Goo Cleaning", "equipment")),
    ("MultiToolCleaningGooChip4", ("Microchip - T4 Goo Cleaning", "equipment")),
    ("OreBreaker1", ("T1 Ore Crusher", "structure")),
    ("OutsideLamp1", ("Outdoor Lamp", "structure")),
    ("OxygenTank1", ("T1 Oxygen Tank", "equipment")),
    ("OxygenTank3", ("T3 Oxygen Tank", "equipment")),
    ("OxygenTank5", ("T5 Oxygen Tank", "equipment")),
    ("Phytoplankton4", ("Phytoplankton D", "plant")),
    ("PinChip1", ("Microchip - T1 Blueprint Pinning", "chip")),
    ("PlanetaryDeliveryDepot1", ("Planetary Delivery Depot", "structure")),
    ("PodUnderground", ("Underground Living Compartment", "structure")),
    ("Poster11", ("Poster K", "furniture")),
    ("Poster12", ("Poster L", "furniture")),
    ("Poster13", ("Poster M", "furniture")),
    ("Poster6", ("Poster F", "furniture")),
    ("RocketAnimals2", ("T2 Animals Spreader Rocket", "rocket")),
    ("RocketDeparture1", ("Extraction Rocket", "rocket")),
    ("RocketHeat2", ("T2 Asteroid Attraction Rocket", "rocket")),
    ("RocketOxygen2", ("T2 Oxygen Rocket", "rocket")),
    ("RocketPurification1", ("Purification Rocket", "rocket")),
    ("RocketToxicInformations1", ("Toxic Area Information Rocket", "rocket")),
    ("Seed0Growable", ("Lirma Plant", "plant")),
    ("Seed1Growable", ("Shanga Plant", "plant")),
    ("Seed2Growable", ("Pestera Plant", "plant")),
    ("Seed3Growable", ("Nulna Plant", "plant")),
    ("Seed4Growable", ("Tuska Plant", "plant")),
    ("SeedGoldGrowable", ("Golden Plant", "plant")),
    ("Skin-04", ("Spacesuit Goldeo", "equipment")),
    ("Skin-08", ("Spacesuit Tureo", "equipment")),
    ("Skin-11", ("Spacesuit Vateo", "equipment")),
    ("Skin-12", ("Spacesuit Widio", "equipment")),
    ("Skin-18", ("Spacesuit Starforma", "equipment")),
    ("Skin-19", ("Spacesuit Glitx", "equipment")),
    ("Skin-20", ("Spacesuit Colonnya", "equipment")),
    ("Skin-22", ("Spacesuit Goox", "equipment")),
    ("Skin-23", ("Spacesuit Alij", "equipment")),
    ("Skin-24", ("Spacesuit Stellarcheo", "equipment")),
    ("StarformContainer", ("Starform Crate", "container")),
    ("StarformEffigie1", ("Starform Effigy", "furniture")),
    ("StarformEffigie2", ("Starform Effigy", "furniture")),
    ("StarformEffigie4", ("Starform Effigy", "furniture")),
    ("StarformEffigie5", ("Starform Effigy", "furniture")),
    ("StarformEffigie6", ("Starform Effigy", "furniture")),
    ("ToxicWaterCollector3", ("T3 Toxic Water Collector", "structure")),
    ("ToxicZoneHudDisplayer", ("Microchip - Toxic Areas Informations", "chip")),
    ("ToxicityDiorama2", ("Terraforming Diorama B", "furniture")),
    ("ToxinsFilter1", ("T1 Toxins Filter", "structure")),
    ("ToxinsFilter3", ("T3 Toxins Filter", "structure")),
    ("TreePlanter", ("Tree Pot", "structure")),
    ("TreePlanter3", ("Giant Trees Pot", "structure")),
    ("VehicleEquipmentSize1", ("Vehicle - T1 Equipment Increase", "vehicle")),
    ("VehicleSpeed4", ("Vehicle - T4 Speed Increase", "vehicle")),
    ("WardenAustel", ("Warden's Altar", "structure")),
    ("WreckSafe", ("Big Safe", "container")),
    ("WreckWardrobe", ("Spacesuits Locker", "container")),
    ("door", ("Living Compartment Door", "structure")),
    ("wallplain", ("Plain Wall", "structure")),
    ("window", ("Living Compartment Window", "structure")),
])

# Items observed in demandGrps/supplyGrps across the sample saves. A future item needs
# one entry in ITEMS and, if logistics-capable, one membership here.
LOGISTICS_IDS = {
    "Algae1Seed", "Alloy", "Aluminium", "Amber", "AnimalBones", "AnimalFood1", "AnimalFood2",
    "AnimalFood3", "AntiToxinsExplosive1", "AntiToxinsExplosive2", "Bacteria1", "BalzarQuartz",
    "Bauxite", "Bee1Larvae", "Bioplastic1", "Butterfly1Larvae", "Butterfly2Larvae",
    "Butterfly3Larvae", "Butterfly4Larvae", "Butterfly5Larvae", "Butterfly6Larvae",
    "Butterfly7Larvae", "Butterfly8Larvae", "Butterfly9Larvae", "Butterfly10Larvae",
    "Butterfly11Larvae", "Butterfly12Larvae", "Butterfly13Larvae", "Butterfly14Larvae",
    "Butterfly15Larvae", "Butterfly16Larvae", "Butterfly17Larvae", "Butterfly18Larvae",
    "Butterfly19Larvae", "Butterfly20Larvae", "Butterfly21Larvae", "ChlorineCapsule1",
    "CircuitBoard1", "Cobalt", "CookCake1", "CookChocolate", "CookCocoaGrowable",
    "CookCocoaSeed", "CookCookie1", "CookCroissant", "CookFlour", "CookStew1", "CookStewFish1",
    "CookWheatGrowable", "CookWheatSeed", "CosmicQuartz", "DNASequence",
    "Dolomite", "Drone1", "Drone2", "Drone3", "Explosive", "FabricBlue", "Fertilizer1", "Fertilizer2",
    "Fertilizer3", "Fish1Eggs", "Fish2Eggs", "Fish3Eggs", "Fish4Eggs", "Fish5Eggs",
    "Fish6Eggs", "Fish7Eggs", "Fish8Eggs", "Fish9Eggs", "Fish10Eggs", "Fish11Eggs",
    "Fish12Eggs", "Fish13Eggs", "Fish14Eggs", "Fish15Eggs", "Flare", "Frog1Eggs",
    "Frog2Eggs", "Frog3Eggs", "Frog4Eggs", "Frog5Eggs", "Frog6Eggs", "Frog7Eggs",
    "Frog8Eggs", "Frog9Eggs", "Frog10Eggs", "Frog11Eggs", "Frog12Eggs", "Frog13Eggs",
    "Frog14Eggs", "Frog15Eggs", "Frog16Eggs", "FrogGoldEggs", "FuseAnimals1", "FuseCartridge",
    "FuseEnergy1", "FuseGrowth1", "FuseHeat1", "FuseInsects1", "FuseOxygen1", "FusePlants1",
    "FusePressure1", "FuseProduction1", "FusePurification1", "FuseTradeRocketsSpeed1",
    "FusionEnergyCell", "GeneticTrait", "Iridium", "Iron", "Keycard1", "KeyCard2",
    "LarvaeBase1", "LarvaeBase2", "LarvaeBase3", "Magnesium", "MagnetarQuartz",
    "MethanCapsule1", "MicroPlastics", "Minable-Tungsten", "Mutagen1", "Mutagen2", "Mutagen3",
    "Mutagen4", "NitrogenCapsule1", "Obsidian", "Osmium", "OxygenCapsule1", "Phosphorus",
    "Phytoplankton1", "Phytoplankton2", "Phytoplankton3", "PlasticPolymer", "PristineMushroom",
    "PulsarQuartz", "PurificationCapsule", "PurificationGel", "PurifiedWater", "QuasarQuartz",
    "RedPowder1", "RocketReactor", "RocketReactor2", "Rod-alloy", "Rod-iridium", "Rod-osmium",
    "Rod-plastic", "Rod-tungsten", "Rod-uranium", "Seed0", "Seed1", "Seed2", "Seed3", "Seed4",
    "Seed5", "Seed6", "Seed7Humble", "Seed8Humble", "Seed9Humble", "Seed10Humble",
    "Seed11Humble", "SeedGold", "Selenium", "Silicon", "Silk", "SilkWorm", "SmartFabric",
    "SolarQuartz", "Sulfur", "Titanium", "ToxicGoo", "ToxicSpores", "ToxicWater",
    "ToxicityAmmo", "ToxicityAmmoPack", "ToxicityMedecine", "ToxicityMedecinePack", "Toxins",
    "Tree0Seed", "Tree1Seed", "Tree2Seed", "Tree3Seed", "Tree4Seed", "Tree5Seed", "Tree6Seed",
    "Tree7Seed", "Tree8Seed", "Tree9Seed", "Tree10Seed", "Tree11Seed", "Tree12Seed",
    "Tree13Seed", "Tree14Seed", "Tree15Seed", "Tree16Seed", "Tree17Seed", "Tree18Seed", "TreeRoot",
    "Uraninite", "Uranim", "Vegetable0Growable", "Vegetable0Seed", "Vegetable1Growable",
    "Vegetable1Seed", "Vegetable2Growable", "Vegetable2Seed", "Vegetable3Growable",
    "Vegetable3Seed", "WaterBottle1", "Zeolite", "astrofood", "astrofood2", "honey", "ice",
    "Phytoplankton4",
}

# gid -> [addedIn, deprecatedIn]. Either may stay None ("version unknown") -- most
# base resources predate the earliest tracked patch notes ("Early Alpha Release,
# 2021-02-16: Initial release, no notes") and have nothing to cite.
# Sourced from the full verbatim developer changelog at
# https://planet-crafter.fandom.com/wiki/Version_history (read in full).
VERSION_INFO = {}


def added(version, *gids):
    for g in gids:
        VERSION_INFO.setdefault(g, [None, None])[0] = version


def deprecated(version, *gids):
    for g in gids:
        VERSION_INFO.setdefault(g, [None, None])[1] = version


# --- v0.3.001 "The Watery Update" (2021-08-12) ---
added("0.3.001",
      "Beacon", "EquipmentIncrease2", "Heater3", "Rod-iridium", "Rod-uranium",
      "ComAntenna", "ScreenMessage", "CraftStation2", "Backpack4", "OxygenTank4", "Alloy")

# --- v0.3.004 "Seed Spreader Update" (2021-09-21) ---
added("0.3.004", "SeedSpreader1")

# --- v0.3.005 "Indoor Ladders Update" (2021-09-27) ---
added("0.3.005", "Ladder")

# --- v0.3.010 "Caves & Biology Update" (2021-12-19) ---
added("0.3.010",
      "Biolab", "Biodome2", "WaterCollector1", "WaterCollector2", "AlgaeGenerator1",
      "AlgaeGenerator2", "Bacteria1", "Fertilizer1", "Bioplastic1", "WaterFilter",
      "OreExtractor1", "Sulfur", "Osmium", "EnergyGenerator5", "HudCompass")

# --- v0.3.011 "Jetpack and Blueprints Update" (2022-01-15) ---
added("0.3.011", "BlueprintT1", "Jetpack1", "Destructor1", "RocketMap1", "ScreenMap1", "RedPowder1")

# --- v0.4.004 Initial EA full release (2022-03-24) ---
added("0.4.004",
      "GasExtractor1", "Jetpack2", "Jetpack3", "Drill3", "Heater4", "Backpack5",
      "OreExtractor2", "VegetableGrower2", "RocketBiomass1", "podAngle", "RecyclingMachine",
      "GrassSpreader1", "SeedSpreader2", "TreeSpreader0", "TreeSpreader1", "TreeSpreader2",
      "Sign", "Mutagen1", "MethanCapsule1", "RocketMap2", "RocketMap3", "FlowerPot1",
      "PulsarQuartz", "Pod4x", "FusionEnergyCell", "DisplayCase", "InsideLamp1", "Zeolite")

# --- v0.4.011 "Caves & Crater" (2022-05-18) ---
added("0.4.011", "Teleporter1", "Rod-alloy", "MultiToolLight2", "RocketInformations1")

# --- v0.4.014 Hotfix (2022-05-25) ---
added("0.4.014", "ScreenRockets")

# --- v0.5.005 "Insects & Waterfall" (2022-07-31) ---
added("0.5.005",
      "ScreenBiomass", "Incubator1", "Beehive1", "ButterflyDome1", "Farm1", "honey",
      "LarvaeBase1", "LarvaeBase2", "LarvaeBase3", "Bee1Larvae", "SilkGenerator",
      "ButterflyFarm1", "ButterflyDisplayer1", "Fence")

# --- v0.6.006 "Lore & Automation Update" (2022-10-16) ---
added("0.6.006",
      "AutoCrafter1", "OreExtractor3", "AirFilter1", "EquipmentIncrease3", "Mutagen2",
      "Rod-osmium", "Heater5", "Drill4", "RocketInsects1", "ButterflyFarm2", "Beehive2",
      "HudChipCleanConstruction")

# --- v0.7.007 "Fish & Drones Update" (2023-03-01) ---
added("0.7.007",
      "DroneStation1", "Drone1", "Mutagen3", "GasExtractor2", "CircuitBoard1",
      "Phytoplankton1", "Phytoplankton2", "Phytoplankton3", "NitrogenCapsule1",
      "GoldenEffigie6", "MultiToolDeconstruct2", "RocketMap4", "RocketDrones1",
      "WaterLifeCollector1", "Aquarium1", "Aquarium2", "FishFarm1")

# --- v0.8.008 "Space Trading Update" (2023-06-27) ---
added("0.8.008",
      "TradePlatform1", "Mutagen4", "TerraTokens100", "TerraTokens500", "TerraTokens1000",
      "TerraTokens5000", "AmphibiansFarm1", "CookStewFish1", "CookStew1", "CookCookie1",
      "CookCake1", "CookCroissant", "Pod9xA", "Pod9xB", "Container3", "Drone2",
      "CookingStation1", "SofaColored", "BedDoubleColored", "CookCocoaSeed", "CookWheatSeed")

# --- v0.9.006 "Volcanic Update" (2023-10-16) ---
added("0.9.006",
      "Optimizer1", "Optimizer2", "FuseHeat1", "FuseEnergy1", "FuseProduction1",
      "FusePressure1", "FuseOxygen1", "FusePurification1", "Obsidian", "WallInside", "MapChip")

# --- v0.9.012 "Quality of Life Update & Treasure Hunt" (2023-11-21) ---
added("0.9.012", "PinChip1", "PinChip2")

# --- v1.0 Release (2024-04-10) ---
added("1.0",
      "GeneticExtractor1", "GeneticSynthetizer1", "AnimalShelter1", "AnimalFeeder1",
      "GeneticTrait", "DNASequence", "RocketAnimals1", "Jetpack4", "Backpack6",
      "MultiToolDeconstruct3", "MultiToolLight3")

# --- v1.102 "The Explosive Update" (2024-05-27) ---
added("1.102", "Ecosystem1", "AnimalFood1", "EquipmentIncrease4", "SkinDisplayer")

# --- v1.211 "The Rover Update" (2024-09-02) ---
added("1.211", "VehicleCrafter1", "FoundationSlope", "FoundationAngle")

# --- v1.310 Planet Humble DLC release (2024-10-09) ---
added("1.310", "EscapePodHumble", "Seed9Humble", "Seed10Humble", "Seed11Humble")

# --- v1.314 Humble improvement patch (2024-10-16) ---
added("1.314", "StarformContainer", "StarformEffigie1")

# --- v1.404 "The Decoration Update" (2024-12-09) ---
added("1.404", "InteriorStairs1")

# --- v1.518 "The Moons Update" (2025-05-19, Selenea + Aqualis) ---
added("1.518",
      "RocketTravel1", "InterplanetaryExchangePlatform1", "PlanetaryDeliveryDepot1",
      "ScreenSystem1", "QuartzCraftStation1", "CosmicQuartz", "Selenium", "Phosphorus",
      "HarvestingRobot1", "RocketInformations2", "RocketReactor2", "RocketBiomass2",
      "Backpack7", "OxygenTank5", "Jetpack5", "Fertilizer3", "RecyclingMachine2",
      "ButterflyFarm3", "Farm2", "FishFarm2", "AnimalFood3", "Megadome1", "VehicleSpeed4",
      "RocketHeat2", "RocketPressure2", "RocketInsects2", "FuseAnimals1", "FuseInsects1",
      "FuseGrowth1", "FuseCartridge")

# --- v1.608 Toxicity DLC release (2025-11-17) ---
added("1.608",
      "ToxicGoo", "ToxicWater", "ToxicSpores", "Toxins", "AntiToxinsExplosive1",
      "AntiToxinsExplosive2", "DetoxificationMachine1", "DetoxificationMachine2",
      "DetoxificationMachine3", "ToxicWaterCollector1", "ToxicWaterCollector2",
      "ToxicWaterCollector3", "ToxinsFilter1", "ToxinsFilter2", "ToxinsFilter3",
      "ToxicityAmmo", "ToxicityAmmoPack", "ToxicityMedecine", "ToxicityMedecinePack",
      "ToxicZoneHudDisplayer", "ToxicZoneHudDisplayer2", "ToxicRefinementCraftStation1",
      "EscapePodToxicity", "ScreenToxic1")

# --- v1.613 Toxicity Patch #4 (2025-12-04) ---
added("1.613", "ContainerToxic1")

# --- v1.617 Toxicity Patch #5-area patch (2026-01-15 notes, "V 1.617") ---
added("1.617", "AnimalEffigie9")  # "Doggox" -- explicitly Toxicity-exclusive creature

# --- v2.102 "2.1 Skeo Update" (2026-09-01) ---
added("2.102",
      "PodUnderground", "Incubator2", "TreePlanter3", "RocketAnimals2", "Tree18Seed",
      "InsideLamp2", "Drone3", "RocketOxygen2", "AnimalEffigie10", "Butterfly21Larvae")
deprecated("2.102", "Phytoplankton2", "Phytoplankton3")


def main():
    out = collections.OrderedDict()
    out["$comment"] = (
        "App-only item catalog keyed by WorldObject.GId. Not part of the save "
        "file. Item entries also define logistics and lifecycle metadata. 'icon' "
        "overrides its category icon; unknown GIds fall back to the raw id and "
        "the fallbackCategory icon. Regenerate with "
        "tools/item-catalog/gen_catalog.py."
    )
    out["fallbackCategory"] = FALLBACK_CATEGORY
    out["categories"] = CATEGORIES
    items = collections.OrderedDict()
    for gid, (name, cat) in ITEMS.items():
        assert cat in CATEGORIES, f"{gid} -> unknown category {cat}"
        logistics_capable = gid in LOGISTICS_IDS
        added_in, deprecated_in = VERSION_INFO.get(gid, (None, None))
        items[gid] = {
            "displayName": name,
            "category": cat,
            "canDemand": logistics_capable,
            "canSupply": logistics_capable,
            "deprecated": deprecated_in is not None,
            "addedIn": added_in,
            "deprecatedIn": deprecated_in,
        }
    unknown_version_ids = set(VERSION_INFO) - set(ITEMS)
    assert not unknown_version_ids, f"VERSION_INFO ids missing from ITEMS: {sorted(unknown_version_ids)}"
    missing_logistics_items = LOGISTICS_IDS.difference(items)
    assert not missing_logistics_items, f"Logistics ids missing from ITEMS: {sorted(missing_logistics_items)}"
    out["items"] = collections.OrderedDict(sorted(items.items(), key=lambda kv: kv[0].lower()))

    text = json.dumps(out, indent=2)
    path = "PCEdit.App.Core/Data/ItemCatalog.json"
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text + "\n")
    print(f"wrote {path}: {len(items)} items, {len(CATEGORIES)} categories")


if __name__ == "__main__":
    main()
