#!/usr/bin/env python3
"""Generate deploy/com.valkerran.pcedit.metainfo.xml (AppStream) from the string catalog.

Summary and description text are pulled from the same tools/i18n/<culture>.json files
that feed gen_satellites.py, so the store listing stays in sync with the in-app text
across all 15 supported locales. Run after editing translations:

    python tools/i18n/gen_metainfo.py
"""
from __future__ import annotations

import json
import pathlib
import sys
from xml.sax.saxutils import escape

ROOT = pathlib.Path(__file__).resolve().parents[2]
I18N = ROOT / "tools" / "i18n"
OUT = ROOT / "deploy" / "com.valkerran.pcedit.metainfo.xml"

APP_ID = "com.valkerran.pcedit"
RELEASE_VERSION = "1.0.0"
RELEASE_DATE = "2026-08-28"

# culture -> AppStream xml:lang. en-US is the neutral/default (no xml:lang attribute).
LOCALES = {
    "en-US": None,
    "en-GB": "en_GB",
    "fr": "fr",
    "de": "de",
    "es-ES": "es",
    "zh-Hans": "zh_Hans",
    "ru": "ru",
    "pl": "pl",
    "pt-PT": "pt_PT",
    "ko": "ko",
    "ja": "ja",
    "pt-BR": "pt_BR",
    "it": "it",
    "zh-Hant": "zh_Hant",
    "tr": "tr",
}

# Canonical en-US strings (mirror PCEdit.App.Core/Resources/Strings.resx).
EN = {
    "Shell_Title": "Planet Crafter Save Editor",
    "About_Tagline": "A save-file editor for The Planet Crafter.",
    "OpenFile_Intro": (
        "Open a Planet Crafter save file to view and edit players, world terraforming, "
        "inventories, terra tokens, and teleport locations."
    ),
    "Disclaimer_Body": (
        "PCEdit edits Planet Crafter save files directly. A bad edit can corrupt a save and "
        "lose progress. Always keep a backup of your save file before editing. This software "
        "is provided as is, without warranty of any kind."
    ),
}

DESC_KEYS = ("About_Tagline", "OpenFile_Intro", "Disclaimer_Body")


def load(culture: str) -> dict[str, str]:
    if culture == "en-US":
        return EN
    data = json.loads((I18N / f"{culture}.json").read_text(encoding="utf-8"))
    # Fall back to English for any key that is missing or blank.
    return {k: (data.get(k) or EN[k]) for k in EN}


def lang_attr(xml_lang: str | None) -> str:
    return "" if xml_lang is None else f' xml:lang="{xml_lang}"'


def main() -> int:
    strings = {c: load(c) for c in LOCALES}

    lines: list[str] = []
    w = lines.append
    w('<?xml version="1.0" encoding="UTF-8"?>')
    w("<!-- Generated by tools/i18n/gen_metainfo.py - do not edit by hand. -->")
    w('<component type="desktop-application">')
    w(f"  <id>{APP_ID}</id>")
    w("  <metadata_license>MIT</metadata_license>")
    w("  <project_license>GPL-3.0-or-later</project_license>")
    w("  <name>PCEdit</name>")

    for culture, xl in LOCALES.items():
        text = strings[culture]["Shell_Title"]
        if xl is not None and text == EN["Shell_Title"]:
            continue  # identical to the neutral entry
        w(f"  <summary{lang_attr(xl)}>{escape(text)}</summary>")

    w("  <description>")
    for culture, xl in LOCALES.items():
        if xl is not None and all(strings[culture][k] == EN[k] for k in DESC_KEYS):
            continue
        for key in DESC_KEYS:
            w(f"    <p{lang_attr(xl)}>{escape(strings[culture][key])}</p>")
    w("  </description>")

    w('  <launchable type="desktop-id">com.valkerran.pcedit.desktop</launchable>')
    w('  <url type="homepage">https://github.com/Valkerran/PCEdit</url>')
    w('  <url type="bugtracker">https://github.com/Valkerran/PCEdit/issues</url>')

    w('  <developer id="com.valkerran">')
    w("    <name>Walter Smart</name>")
    w("  </developer>")

    w("  <categories>")
    w("    <category>Utility</category>")
    w("    <category>Game</category>")
    w("  </categories>")

    w("  <keywords>")
    for kw in ("Planet Crafter", "save editor", "terraforming", "inventory", "game save"):
        w(f"    <keyword>{escape(kw)}</keyword>")
    w("  </keywords>")

    w('  <content_rating type="oars-1.1" />')

    w("  <languages>")
    for culture, xl in LOCALES.items():
        code = "en" if culture == "en-US" else xl
        w(f'    <lang percentage="100">{code}</lang>')
    w("  </languages>")

    w("  <releases>")
    w(f'    <release version="{RELEASE_VERSION}" date="{RELEASE_DATE}">')
    w("      <description>")
    w("        <p>First public release: the Avalonia desktop build, packaged as a "
      "self-contained AppImage.</p>")
    w("      </description>")
    w("    </release>")
    w("  </releases>")

    w("</component>")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(LOCALES)} locales)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
